### ISSUE TITLE
Bug with extensible predicates and parallel executor

### ISSUE THREAD

**Issue by tmoux** [HarvardPL/AbcDatalog#11]
I tried running the "ExecutorExample" program and encountered this exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: Predicate true is not marked as extensible.
	at edu.harvard.seas.pl.abcdatalog.engine.bottomup.concurrent.ExtensibleBottomUpEvalManager.addFact(ExtensibleBottomUpEvalManager.java:182)
	at edu.harvard.seas.pl.abcdatalog.engine.bottomup.concurrent.ExtensibleBottomUpEvalManager.eval(ExtensibleBottomUpEvalManager.java:123)
	at edu.harvard.seas.pl.abcdatalog.executor.DatalogParallelExecutor.start(DatalogParallelExecutor.java:90)
	at edu.harvard.seas.pl.abcdatalog.executor.ExecutorExample.main(ExecutorExample.java:122)
```

After some poking around I found there is a fact "true" that always gets added to the list of initial facts:
https://github.com/HarvardPL/AbcDatalog/blob/493d24a8885adc18beb1a5168dc4d338a9bc2c2d/src/main/java/edu/harvard/seas/pl/abcdatalog/ast/validation/DatalogValidator.java#L101

The example uses the DatalogParallelExecutor, which uses the ExtensibleBottomUpEvalManager.
The exception is thrown here when trying to add the "true" fact:
https://github.com/HarvardPL/AbcDatalog/blob/493d24a8885adc18beb1a5168dc4d338a9bc2c2d/src/main/java/edu/harvard/seas/pl/abcdatalog/engine/bottomup/concurrent/ExtensibleBottomUpEvalManager.java#L179-L183

In the example file, the executor is initialized here:
https://github.com/HarvardPL/AbcDatalog/blob/493d24a8885adc18beb1a5168dc4d338a9bc2c2d/src/main/java/edu/harvard/seas/pl/abcdatalog/executor/ExecutorExample.java#L94-L95

However, there doesn't seem to be a way to add the "true" predicate here as it is private.
Thus, it seems this exception will occur whenever the DatalogParallelExecutor is used.

**Comment by aaronbembenek** [comment]
Thanks for identifying this and diagnosing the problem! I suspect the `true` fact was added to handle some corner cases with negation and then `DatalogParallelExecutor` wasn't subsequently tested (since it doesn't support negation). I've created a bunch of issues (#12, #13, #14) to avoid this in the future.
